# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Sonos.Controller
PackageVersion: 90.0.67300
Platform:
- Windows.Desktop
InstallerType: exe
Scope: machine
InstallModes:
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /s /v/qn
  SilentWithProgress: /s /v/qb
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x86
    MinimumVersion: 14.24.28127.4
ProductCode: 6FB7DAEC-5DAD-491E-9951-4684423F291C
AppsAndFeaturesEntries:
- InstallerType: msi
Installers:
- Architecture: x86
  InstallerUrl: https://update-software.sonos.com/software/Lp7WoQPkxr/Sonos_90.0-67300.exe
  InstallerSha256: 1A90FB565D9A2D077AF52441D1F66312CA134A4732AD0C084587F72BDC4E14D0
ManifestType: installer
ManifestVersion: 1.10.0
